services:
  # 🌐 Reverse proxy (same as production)
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - webproxy

  # 🔒 ACME (Let’s Encrypt) companion in staging mode
  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-acme-companion
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=derek.dreblow@gmail.com
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - webproxy

  # 🧱 Dreblow Designs container
  test_dreblowdesigns:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: dreblowdesigns
    environment:
      - VIRTUAL_HOST=www.dreblowdesigns.127.0.0.1.nip.io,dreblowdesigns.127.0.0.1.nip.io
      - LETSENCRYPT_HOST=www.dreblowdesigns.127.0.0.1.nip.io,dreblowdesigns.127.0.0.1.nip.io
      - LETSENCRYPT_EMAIL=derek.dreblow@gmail.com
    volumes:
      - /Users/derekdreblow/Git/WebSites/WebSite_DreblowDesigns:/var/www/html:ro
      - ../../support/services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/dreblowdesigns.com/extra-rules.conf:/etc/nginx/conf.d/extra-rules/extra-rules.conf:ro
    networks:
      - webproxy
    command: /bin/sh -c "rm -f /etc/nginx/sites-enabled/default && supervisord -n"

networks:
  webproxy:
    external: true