services:
  test-nginx:
    build:
      context: ../../ 
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /Users/derekdreblow/Git/WebSites/WebSite_DreblowandAssociates:/var/www/html:ro
      - ../../support/services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    command: /bin/sh -c "rm -f /etc/nginx/sites-enabled/default && supervisord -n"